config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: :index
  resources :groups, only: [:index, :new, :create, :edit, :update] do
    resources :messages, only: [:index, :create]
  end
  root to: "groups#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :messages
  has_many :group_users
  has_many :users, through: :group_users

  accepts_nested_attributes_for :users

  validates :name, presence: true
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :group
  belongs_to :user

  validates :body, presence: true
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :group_users
  has_many :groups, through: :group_users
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?


  def after_sign_out_path_for(resources)
    new_user_session_path
  end

  def after_sign_in_path_for(resources)
    root_path
  end


  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      respond_to do |format|
        format.html {redirect_to group_messages_path(group_id: @group.id), notice: "グループを保存しました"}
        format.json {render json: @group}
      end

    else
      flash.now[:alert] = "保存できませんでした"
      render new_group_path
    end
  end

  def edit
    set_group
  end

  def update
    set_group
    if @group.update(group_params)
      move_to_index
    else
      render action: :edit
    end
  end



  private
    def group_params
      params.require(:group).permit(:name, user_ids:[])
    end

    def set_group
      @group = Group.find(params[:id])
    end

    def move_to_index
      redirect_to root_path
    end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_group, only: [:index, :create]
  before_action :set_messages, only: [:index]
  def index
    respond_to do |format|
      format.html
      format.json {render json: @messages}
    end
    @message = Message.new
  end

  def create
    @message = current_user.messages.new(message_params)
    if @message.save
      respond_to do |format|
        format.html {redirect_to group_messages_path, notice: "メッセージを保存しました"}
        format.json {render json: @message}
      end
    else
      set_messages
      flash.now[:alert] = "メッセージが書かれていなかったため、保存できませんでした。"
      render :index
    end
  end

  private
  def message_params
    params.require(:message).permit(:body, :image, :image_cache).merge(group_id: params[:group_id])
  end

  def set_group
    @group = Group.find(params[:group_id])
  end

  def set_messages
    @messages = @group.messages.order("id DESC")
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
    respond_to do |format|
      format.html
      format.json {render json: @users}
    end
  end

end

app/views/groups/_form.html.haml
= form_for(@group) do |f|
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label :name, "グループ名", class: 'chat-group-form__label'
    .chat-group-form__field--right
      = f.text_field :name, placeholder: "グループ名を入力してください", class: 'chat-group-form__input'
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label :チャットメンバー追加, class: 'chat-group-form__label'
    .chat-group-form__field--right
      .chat-group-form__search.clearfix
        %input#user-search-field.chat-group-form__input{ placeholder:'追加したいユーザー名を入力してください', type:'text'}
      #user-search-result
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label :name, "チャットメンバー",  class: 'chat-group-form__label'
    .chat-group-form__field--right
      #chat-group-users
        #chat-group-user.chat-group-user.clearfix
          = f.hidden_field :user_ids, class: 'chat-group-form_hidden'
          %p.chat-group-add-user__name{ id: current_user.id}
            =current_user.name
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
    .chat-group-form__field--right
      = f.submit :Save, class: 'chat-group-form__action-btn'

app/views/groups/_group.html.haml
= form_for(@group) do|f|
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label :グループ名, class: 'chat-group-form__label'
    .chat-group-form__field--right
      = f.text_field :name, placeholder: "グループ名を入力してください", id: 'chat_group_name', class: 'chat-group-form__input'
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      / = f.label :チャットメンバー追加, class: 'chat-group-form__label'
    .chat-group-form__field--right
      .chat-group-form__search.clearfix
        / = f.text_field :name, placeholder: "追加したいユーザー名を入力してください", id: 'user-search-field', class: 'chat-group-form__input'
      #user-search-result
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label :チャットメンバー, class: 'chat-group-form__label'
    .chat-group-form__field--right
      = f.label :users
      = collection_check_boxes(:group, :user_ids, User.all, :id, :name) do|t|
        =t.label{t.check_box + t.text}
    - if request.path_info = new_group_path
      #chat-group-users
      #chat-group-user-22.chat-group-user.clearfix
        = f.hidden_field :'chat_group[user_ids]', value: '22'
        %p.chat-group-user__name seo_kyohei
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
    .chat-group-form__field--right
      = f.submit :Save, name:"commit", class: 'chat-group-form__action-btn', disable_with: 'Save'

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = render partial: 'form'

app/views/groups/index.html.haml
.chat
  .chat-side
    .chat-user.clearfix
      %h5
        =current_user.name
      .chat-user__actions
        = link_to new_group_path, class: 'chat-user__action' do
          %i.fa.fa-pencil-square-o
        = link_to edit_user_registration_path, class: 'chat-user__action' do
          %i.fa.fa-cog
    %ul.chat-groups
      %li.chat-group
        - current_user.groups.each do |group|
          = link_to group_messages_path(group_id: group.id), class: 'chat-group__link' do
            %p.chat-group__name
            =group.name
            %p.chat-group__message 面白い

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = render partial: 'form'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ChatSpace
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %p.notice= notice
    %p.alert= alert
    = yield

app/views/messages/index.html.haml
.chat
  .chat-side
    .chat-user.clearfix
      %h5
        =current_user.name
      .chat-user__actions
        = link_to new_group_path, class: 'chat-user__action' do
          %i.fa.fa-pencil-square-o
        = link_to edit_user_registration_path, class: 'chat-user__action' do
          %i.fa.fa-cog
    %ul.chat-groups
      %li.chat-group
        - current_user.groups.each do |group|
          = link_to group_messages_path, class: 'chat-group__link' do
            %p.chat-group__name
            =group.name
            %p.chat-group__message
              面白い
  .chat-main
    .chat-header.clearfix
      .chat-header__left
        %h2
        =@group.name
        %p.chat-header__users
          Members:
          %span.chat-header__user
          = @group.name
      .chat-header__right
        = link_to "Edit", edit_group_path(id: current_user.id), class: "chat-header__edit-btn"
    .chat-body
      %ul.chat-messages
        - @messages.each do |message|
          %li.chat-message
            .chat-message__header.clearfix
              %p.chat-message__name
                =message.user.name
              %p.chat-message__time
                =message.created_at.strftime("%Y-%m-%d %H:%M:%S")
            %p.chat-message__body
              =message.body
            - if message.image?
              = image_tag message.image.url, class: ".chat-message__image"
    .chat-footer
      = form_for [@group, @message] do |f|
        .chat-footer__body
          = f.text_area :body
          = f.label :image, class: 'chat-footer__file' do
            %i.fa.fa-image
          = f.file_field :image, style: "display: none;"
          = f.hidden_field :image_cache
        = f.submit "Send", id: 'submit'